# Generated by Django 3.1.7 on 2021-02-25 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='', editable=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ForumMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='forums.forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_forums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('forum', 'user')},
            },
        ),
        migrations.AddField(
            model_name='forum',
            name='members',
            field=models.ManyToManyField(through='forums.ForumMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
